#defining a simple model

In [27]:
import tensorflow as tf
from tensorflow import keras

In [28]:
#y=3 * x - 5
x=tf.constant([-1,-2,0,1,2,5,7], dtype=float)
y=x*3-5
yy=tf.constant([-8,-11,-5,-2,1,10,16], dtype=float)

In [29]:
x.numpy()

array([-1., -2.,  0.,  1.,  2.,  5.,  7.], dtype=float32)

In [30]:
y.numpy()


array([ -8., -11.,  -5.,  -2.,   1.,  10.,  16.], dtype=float32)

In [31]:
yy.numpy()

array([ -8., -11.,  -5.,  -2.,   1.,  10.,  16.], dtype=float32)

In [32]:
#model definition
model=keras.Sequential([
    keras.layers.Dense(units=1,activation=None,input_shape=[1])
    ])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
#(y- y-pred)^2
model.compile(optimizer='sgd',loss='mean_squared_error')

In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                      │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.fit(x,yy,batch_size=1,epochs=100)

Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 65.4565 
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0354
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.5405 
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15.6966 
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1789 
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4860 
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1694  
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.1657 
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.9976 
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2635 
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8724 
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.2588 
Epoch 13/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.1135 
Epoch 14/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7292 
Epoch 15/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6051 
Epoch 16/100
7/

#test

In [36]:
#y=3*x-5
x_test= tf.constant([-4,11,20],dtype=float)
#y_test=x_test*3-5

In [37]:
#y_test.numpy()

In [38]:
y_pred=model.predict(x_test)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[-16.999805],
       [ 27.99997 ],
       [ 54.999832]], dtype=float32)