In [3]:
import numpy as np

In [4]:
#create array  , matrix
a=np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
b= np.array([[1,2],[3,4]])


In [6]:
#shape: be ma abaade mokhtalefe list ro be ma bar migardanad
print(a.shape , b.shape)

(4,) (2, 2)


In [7]:
#reshape بخاطر اینکه ماتریس اولی رو چون فقط یک بعد داشت اینجوری به 
# (4،) نشون میده که باعث دردسر هست پس از ریشیپ استفاده میکنیم
c=a.reshape((4,1))
c

array([[1],
       [2],
       [3],
       [4]])

In [8]:
print(c.shape , b.shape)

(4, 1) (2, 2)


In [9]:
d=a.reshape((2,2,1))
d

array([[[1],
        [2]],

       [[3],
        [4]]])

In [10]:
d.shape

(2, 2, 1)

In [11]:
d=a.reshape((2,-1,1))
d.shape


(2, 2, 1)

In [13]:
#contacanate برای چسباندن دو لیست به هم استفاده میشود
a=np.array([1,2,3])
b=np.array([4,5])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [17]:
#ضرب و جمع و اینای در لیستها
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
c
d=a*b
print(c, d)

[5 7 9] [ 4 10 18]


In [19]:
#broad casting in Numpy  یعنی مثال زیر که یک لیست 1 در 1 در لیست 1 در 3 جمع یا ضرب میشه 
# و به شکل زیر در می آید
c=np.array([10])
d=a+c
e=a+5
print(d,e)

[11 12 13] [6 7 8]


In [20]:
#  slice    چجوری یه بخش خاصی از لیست را انتخاب کنیم 
a=np.array([1,2,3,4,5,6,7,8])
a.shape


(8,)

In [22]:
b=a[2:7]
c=a[0:5]
print(b,c)

[3 4 5 6 7] [1 2 3 4 5]


In [24]:
#اگه بخوام طول گام رو مشخص کنیم ، یک بعد دیگه هم اضافه میکنیم مثل زیر
b=a[2:7:2]
b

array([3, 5, 7])

In [25]:
#برای اینکه اعداد بزرگتر از مقدار 3 رو که در لیست در بیاریم مثل زیر عمل میکنیم
c=a[a>3]
c

array([4, 5, 6, 7, 8])

In [27]:
#جمع تمامی اعضای لیست رو بهمون میده
sum_a=np.sum(a)
sum_a

np.int64(36)

In [28]:
#بزرگترین المان داخل لیست رو بهمون میده
max_a=np.max(a)
max_a

np.int64(8)

In [29]:
#کوچکترین المان داخل لیست رو بهمون میده
min_a=np.min(a)
min_a

np.int64(1)

In [30]:
#روش مرتب سازی لیست ما
b=np.array([8,5,1,9,3,2,6])
sort_b=np.sort(b)
sort_b

array([1, 2, 3, 5, 6, 8, 9])

In [32]:
#چگونه یک ماتریس رندوم درست کنیم
#مقدار اول دوم برای رنج اعداد و مقدار سوم و چهارم برای تعیین ابعاد ماتریس است
a=np.random.randint(0,10,(3,4))
a

array([[3, 2, 3, 7],
       [0, 8, 1, 0],
       [4, 7, 2, 2]], dtype=int32)

In [33]:
#اگر بخواهیم دو لیست رو بصورت استک  رو هم بگذاریم با دستور زیر اینکارو میکنیم 
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.vstack((a,b))
c
#علت اینکه در داخل پرانترز دوباره یه پرانترز دیگه میزاریم اینه که با تاپل 
# طرف هستیم و  این دستور و دستور کانکنکیت رو وقتی استفاده میکنیم باید اینجوری بنویسیم

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
#farghe in vstack and hstack in ast ke vstask be sorat vertically inaro kenare ham mizare vali hstack inaro besorate ofoghi
#mizare ke alan tafavotesho midonim 
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.hstack((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
#baraye be dast avardane normalize bayad mean va enherafe meyaro bedast biarim pas az dastor zir baraye mean estefade mikonim
c=np.array([1,2,3])
mean_c=np.mean(c)
mean_c

np.float64(2.0)

In [43]:
#baraye inke enherafe meyaaro be dast biarim ham az dastore zir estefade mikonim.
std_c=np.std(c)
std_c

np.float64(0.816496580927726)

In [44]:
#hala baraye normalize kardan bayad az formole zir estefade konim
norm_c=(c-mean_c)/std_c
norm_c

array([-1.22474487,  0.        ,  1.22474487])

In [45]:
#normalize kardan yani miangin ro be samte sefr shift bedim 
np.mean(norm_c)


np.float64(0.0)

In [47]:
#normalize kardan yani enheraf meyaro be samte sefr shift bedim
np.std(norm_c)

np.float64(0.9999999999999999)